### ISSUE TITLE
Add view events history

### ISSUE THREAD

**Issue by lucipeterson** [codeforgoodconf/sisters-of-the-road-admin#101]
I suggest adding the ability to view the barter event history for an account on the account page so the user can research account balance issues, answer customer questions about the account balance, correct any errors that were made on the account.   Currently, the user can only see the date of the most recent transaction.

**Comment by jarrighi** [comment]
Thanks, @lucipeterson! I like this suggestion, but the cafe would prefer the full history to be viewable by the admin staff only, rather than the cashier staff. Then, if the customer has any concerns about their history, the admin could work on correcting them. I'm going to mark this resolved.
