### ISSUE TITLE
Make accounts work with Dollars and cents instead of cents

### ISSUE THREAD

**Issue by mikelane** [codeforgoodconf/sisters-of-the-road-admin#109]
Working with cents on the back end is error-prone. We should make the model work with dollars and cents and prevent rounding errors while doing so.

**Comment by bakersemail** [comment]
Hi Mikelane,
I'd have to disagree on this. Dollars are just a representation of the base currency, in this case is cents. Dealing with dollars is error prone to rounding errors.

**Comment by mikelane** [comment]
The monetary values are rounded to the nearest 25 cents, so I'm not sure how rounding errors would be an issue. Also, yeah, Django-money is based on python's Decimal(), so nbd there.
