### ISSUE TITLE
Create credit and debit APIs

### ISSUE THREAD

**Issue by meli-lewis** [codeforgoodconf/sisters-of-the-road-admin#17]

**Comment by meli-lewis** [comment]
- [ ] Respond to a  `GET` request with a simple HTML page
- [ ] Respond to a `POST` request with a simple HTML page
- [ ] Apply `POST` to interaction with the database, maybe simply with 200 or failure
- [ ] Handle `POST` with information from database, like barter account name and balance

**Comment by jarrighi** [comment]
@harveyam or @meli-lewis Wanna update this one?
