### ISSUE TITLE
Dollar input validation

### ISSUE THREAD

**Issue by afisher** [codeforgoodconf/sisters-of-the-road-admin#39]
The input fields on the AddCredit and BuyMeal pages currently do not have any validation. It would be nice to display a helpful message if the user tries to submit something invalid.

Also, Eileen suggested adding a "mask" to the input so that e.g. if the user types "125" the field automatically formats that as "$1.25". This is a non-trivial problem though, and might be better suited to its own issue.

**Comment by scholachoi** [comment]
In progress. Started on this while working on balance limits. (Did not realize it was a separate issue.) So far, made it so that user cannot enter a negative number on AddCredit page.

**Comment by scholachoi** [comment]
Error messages are displayed if user enters negative amount, amount not in increment of $.25, or if amount would exceed account balance. See issues #54 and #59. Made new issue #66 for the second part of this issue.
