### ISSUE TITLE
Change "Django administration" to "Sisters of the Road Cafe Admin"

### ISSUE THREAD

**Issue by jarrighi** [codeforgoodconf/sisters-of-the-road-admin#41]
In the admin interface, the current page heading is "Django administration". 

It would be better to change this to something more specific, something like "Sisters of the Road Cafe Admin".

Since this is in the django admin, you won't find this heading in our existing code, but it should be relatively straight forward to find out how to do this using Django's documentation.

**Comment by razzlepdx** [comment]
Is it ok if I assign myself to this one?  I'd like to learn more about Django admin.

**Comment by jarrighi** [comment]
That would be excellent!
