### ISSUE TITLE
Use Tachyons for styling

### ISSUE THREAD

**Issue by afisher** [codeforgoodconf/sisters-of-the-road-admin#45]
I would like to propose switching our styling over to http://tachyons.io/
I have been using Tachyons for some personal stuff, and as someone who hates writing CSS, it has been a lifesaver. I believe that switching will allow us to keep our styling simple, easy to update, and help us remain consistent with multiple contributors.

To complete this, you will need to:

- [x] Include tachyons.css in our index.html
- [x] Remove the existing CSS (bartercheckout.css)
- [x] Replace all class names in the React component render() functions with tachyons class names

**Comment by razzlepdx** [comment]
I'm going to remove myself from this issue in case someone wants to tackle it this weekend at the group meetup.

**Comment by jarrighi** [comment]
@afisher Could you clarify what benefit tachyons has over bootstrap? I'm not against it, I'm just not understanding the problem it solves from the bit of reading I've done. We're not really using the full potential of bootstrap now, and I'd rather stick to libraries and frameworks that are widely used as long as they work for us.

**Comment by afisher** [comment]
I've personally found tachyon's easier and simpler to use. The kind of "customization" we need to do to the UI isn't a ton, but we already have a fair amount of CSS and that is just going to keep growing and being a thing we have to maintain. I believe that if we switch to tachyons, we actually won't need to write any CSS at all.

It's also much, much more lightweight than bootstap, which is pretty overkill for our needs.

**Comment by jarrighi** [comment]
Okay cool, I'm still pretty skeptical, but I may just be set in my bootstrappy ways. I want to do some work on the UI, so I'll take this one.
