### ISSUE TITLE
[Suggestion] Switch to Preact

### ISSUE THREAD

**Issue by bakersemail** [codeforgoodconf/sisters-of-the-road-admin#47]
This is just a suggestion, but should this project be using Preact instead of React?

React has a restrictive license and is also a larger payload than Preact. Many of the features still exist in Preact, but there are differences which you might need to be aware of.

**Comment by afisher** [comment]
Hi, thanks for the suggestion! I agree that Preact is probably a slightly better fit for this project's needs, and switching over at this point is relatively painless.
