### ISSUE TITLE
Make "Back to Search" smarter

### ISSUE THREAD

**Issue by mikelane** [codeforgoodconf/sisters-of-the-road-admin#94]
When in a barter account, when you click "Back to Search" there is a name populated in the search bar. However, if you click search without changing the name, you get search results that are equivalent to searching for no name (i.e. you get all names returned). If you change even one letter in the name and then click search, you will then get search results with that name.

**Comment by jarrighi** [comment]
Looks like this was fixed. Closing the issue.
